icon-filename: icon.png
icon-position-x: 0
icon-position-y: 0
icon-dimension-x: 70
icon-dimension-y: 70

module-color: '000000'

description: Hard Disk information
description-position-x: 75
description-position-y: 24

start-drawing-offset: 70
horizontal-spacing: 15

partitions-list:
  - '/dev/sda1'
  - '/dev/sda3'
  - '/dev/sdb1'

table-header: 'Filesystem   Type    Size      Used      Free    Used(%)   mount-point'

# time to refresh the component (seconds)
refresh-time: 10