widget-width: 400
widget-height: 900

widget-position-x: 1400
widget-position-y: 120

sand-modules-to-load:
  - module:
      module-name: sand.modules.cpu.gui
      class-name: SandCPUGui
      position-x: 0
      position-y: 0

  - module:
      module-name: sand.modules.memory.gui
      class-name: SandMemoryGui
      position-x: 0
      position-y: 200

  - module:
      module-name: sand.modules.hard_drives.gui
      class-name: SandHardDrivesGui
      position-x: 0
      position-y: 390

  - module:
      module-name: sand.modules.network.gui
      class-name: SandNetworkGui
      position-x: 0
      position-y: 550
