widget-width: 380
widget-height: 800

widget-position-x: 1500
widget-position-y: 100

sand-modules-to-load:
  - module:
      module-name: sand.modules.cpu.gui
      class-name: SandCPUGui
      position-x: 0
      position-y: 0

  - module:
      module-name: sand.modules.memory.gui
      class-name: SandMemoryGui
      position-x: 0
      position-y: 180

  - module:
      module-name: sand.modules.hard_drives.gui
      class-name: SandHardDrivesGui
      position-x: 0
      position-y: 370

