icon-filename: icon.png
icon-position-x: 0
icon-position-y: 0
icon-dimension-x: 50
icon-dimension-y: 50

module-color: '000000'

description: Network information
description-position-x: 60
description-position-y: 18

start-drawing-offset: 60
horizontal-spacing: 15

interfaces:
  ethernet: [enp3s0]
  wifi: [wlp2s0]

disconnection-color: '0059ff'

statistics-script: export_network_stat.sh

ethernet-down-icon-filename: ethernet_down.png
ethernet-up-icon-filename: ethernet_up.png
wifi-down-icon-filename: wifi_down.png
wifi-up-icon-filename: wifi_up.png
interface-status-dimension-x: 60
interface-status-dimension-y: 60

left-padding-interface-status: 20


# time to refresh the component (seconds)
refresh-time: 1